window.SMARTROSARY_VERSION = "v1.58";
window.SMARTROSARY_LANG_VERSION = "v1.37";
window.SMARTROSARY_BREAKING_CHANGES = {
  "versions": { "before": "v1.49" },
  "messages": {
  "en": "This release changes the wallpaper filesystem. As a result, after upgrading from any firmware version prior to v1.49, the wallpaper filesystem (including all stored wallpapers) will be erased.\n\nSince this release significantly improves the wallpaper upload process through both the app and the dashboard, you will need to reinstall your wallpapers after the firmware upgrade. You can either select them again from the built-in presets or re-upload your previously transferred custom wallpapers.\n\nAdditionally, the history filesystem has been updated. During the upgrade, the existing history entries will be migrated automatically. Although the migration is designed to preserve your data, it is strongly recommended to create a full Rosary backup (using either the app or the dashboard) before upgrading. If the history becomes corrupted for any reason, you can restore it from this backup afterward.\n\nPlease note that the backup does not include wallpapers. Preset wallpapers are not backed up, and no wallpapers (preset or custom) are restored as part of the backup restore process.",
  "de": "Dieses Update bringt OTA-Upgrade-Statusbildschirme auf dem Gerät selbst und verbessert die Zuverlässigkeit der RTC-Synchronisation.\n\nZusätzlich wurde das Verlaufs-Dateisystem aktualisiert. Während des Upgrades werden die vorhandenen Verlaufseinträge automatisch migriert. Obwohl die Migration darauf ausgelegt ist, Ihre Daten zu erhalten, wird dringend empfohlen, vor dem Upgrade ein vollständiges Rosary-Backup (über die App oder das Dashboard) zu erstellen. Falls der Verlauf aus irgendeinem Grund beschädigt wird, können Sie ihn anschließend aus diesem Backup wiederherstellen.\n\nBitte beachten Sie, dass das Backup keine Hintergrundbilder enthält. Voreingestellte Hintergrundbilder werden nicht gesichert, und es werden keine Hintergrundbilder (weder voreingestellte noch benutzerdefinierte) als Teil der Backup-Wiederherstellung wiederhergestellt.",
  "pl": "Ta aktualizacja wprowadza ekrany statusu aktualizacji OTA na samym urządzeniu i poprawia niezawodność synchronizacji RTC.\n\nDodatkowo zaktualizowano system plików historii. Podczas aktualizacji istniejące wpisy historii zostaną automatycznie poddane migracji. Chociaż migracja ma na celu zachowanie danych, zdecydowanie zaleca się utworzenie pełnej kopii zapasowej różańca (za pomocą aplikacji lub panelu nawigacyjnego) przed aktualizacją. Jeśli historia ulegnie uszkodzeniu z jakiegokolwiek powodu, można ją następnie przywrócić z tej kopii zapasowej.\n\nNależy pamiętać, że kopia zapasowa nie obejmuje tapet. Fabrycznie zainstalowane tapety nie są archiwizowane i żadne tapety (fabryczne ani niestandardowe) nie są przywracane w ramach procesu przywracania kopii zapasowej.",
  "fr": "Cette mise à jour apporte des écrans d'état de mise à niveau OTA sur l'appareil lui-même et améliore la fiabilité de synchronisation RTC.\n\nDe plus, le système de fichiers de l'historique a été mis à jour. Pendant la mise à niveau, les entrées d'historique existantes seront migrées automatiquement. Bien que la migration soit conçue pour préserver vos données, il est fortement recommandé de créer une sauvegarde complète du Rosaire (en utilisant l'application ou le tableau de bord) avant la mise à niveau. Si l'historique est corrompu pour une raison quelconque, vous pourrez le restaurer à partir de cette sauvegarde par la suite.\n\nVeuillez noter que la sauvegarde n'inclut pas les fonds d'écran. Les fonds d'écran prédéfinis ne sont pas sauvegardés et aucun fond d'écran (prédéfini ou personnalisé) n'est restauré dans le cadre du processus de restauration de la sauvegarde.",
  "es": "Esta actualización trae pantallas de estado de actualización OTA en el propio dispositivo y mejora la fiabilidad de sincronización RTC.\n\nAdemás, el sistema de archivos del historial ha sido actualizado. Durante la actualización, las entradas del historial existentes se migrarán automáticamente. Aunque la migración está diseñada para preservar sus datos, se recomienda encarecidamente crear una copia de seguridad completa del Rosario (usando la aplicación o el panel de control) antes de actualizar. Si el historial se corrompe por algún motivo, puede restaurarlo posteriormente desde esta copia de seguridad.\n\nTenga en cuenta que la copia de seguridad no incluye fondos de pantalla. Los fondos de pantalla preestablecidos no se guardan en la copia de seguridad, y no se restaura ningún fondo de pantalla (preestablecido o personalizado) como parte del proceso de restauración.",
  "pt": "Esta atualização traz telas de status de atualização OTA no próprio dispositivo e melhora a confiabilidade da sincronização RTC.\n\nAlém disso, o sistema de arquivos do histórico foi atualizado. Durante a atualização, as entradas do histórico existentes serão migradas automaticamente. Embora a migração seja projetada para preservar seus dados, é altamente recomendável criar um backup completo do Rosário (usando o aplicativo ou o painel de controle) antes de atualizar. Se o histórico for corrompido por qualquer motivo, você poderá restaurá-lo a partir deste backup posteriormente.\n\nObserve que o backup não inclui papéis de parede. Os papéis de parede predefinidos não fazem parte do backup e nenhum papel de parede (predefinido ou personalizado) é restaurado como parte do processo de restauração do backup."
  }
};
window.SMARTROSARY_RELEASE_MESSAGE = {
  "en": "Firmware v1.58 fixes intention roller preloading according to scheduler settings and refines history intention flagging on manual roller selection.",
  "de": "Firmware v1.58 behebt das Vorladen des Anliegen-Rollers gemäß Scheduler-Einstellungen und verfeinert die Anliegen-Historienkennzeichnung bei manueller Rollerauswahl.",
  "pl": "Firmware v1.58 naprawia wstępne ładowanie na rolce intencji zgodnie z harmonogramem oraz dopracowuje oznaczanie intencji w historii przy ręcznym wyborze.",
  "fr": "Le firmware v1.58 corrige le préchargement du rouleau d'intentions selon le planificateur et affine le marquage des intentions dans l'historique.",
  "es": "El firmware v1.58 corrige la precarga del rodillo de intenciones según el programador y refina el marcado de intenciones en el historial.",
  "pt": "O firmware v1.58 corrige o pré-carregamento do rolo de intenções de acordo com o agendador e aprimora a marcação de intenções no histórico."
};
