window.SMARTROSARY_VERSION = "v1.54";
window.SMARTROSARY_LANG_VERSION = "v1.35";
window.SMARTROSARY_BREAKING_CHANGES = {
  "versions": { "before": "v1.49" },
  "messages": {
  "en": "This release changes the wallpaper filesystem. As a result, after upgrading from any firmware version prior to v1.49, the wallpaper filesystem (including all stored wallpapers) will be erased.\n\nSince this release significantly improves the wallpaper upload process through both the app and the dashboard, you will need to reinstall your wallpapers after the firmware upgrade. You can either select them again from the built-in presets or re-upload your previously transferred custom wallpapers.\n\nAdditionally, the history filesystem has been updated. During the upgrade, the existing history entries will be migrated automatically. Although the migration is designed to preserve your data, it is strongly recommended to create a full Rosary backup (using either the app or the dashboard) before upgrading. If the history becomes corrupted for any reason, you can restore it from this backup afterward.\n\nPlease note that the backup does not include wallpapers. Preset wallpapers are not backed up, and no wallpapers (preset or custom) are restored as part of the backup restore process.",
  "de": "Dieses Update \u00e4ndert das Wallpaper-Dateisystem. Daher wird nach dem Upgrade von einer Firmware-Version vor v1.49 das Wallpaper-Dateisystem (einschlie\u00dflich aller gespeicherten Hintergrundbilder) gel\u00f6scht.\n\nDa diese Version den Prozess zum Hochladen von Hintergrundbildern \u00fcber die App und das Dashboard erheblich verbessert, m\u00fcssen Sie Ihre Hintergrundbilder nach dem Firmware-Upgrade neu installieren. Sie k\u00f6nnen sie entweder erneut aus den integrierten Voreinstellungen ausw\u00e4hlen oder Ihre zuvor \u00fcbertragenen benutzerdefinierten Hintergrundbilder erneut hochladen.\n\nZus\u00e4tzlich wurde das Verlaufs-Dateisystem aktualisiert. W\u00e4hrend des Upgrades werden die vorhandenen Verlaufseintr\u00e4ge automatisch migriert. Obwohl die Migration darauf ausgelegt ist, Ihre Daten zu erhalten, wird dringend empfohlen, vor dem Upgrade ein vollst\u00e4ndiges Rosary-Backup (\u00fcber die App oder das Dashboard) zu erstellen. Falls der Verlauf aus irgendeinem Grund besch\u00e4digt wird, k\u00f6nnen Sie ihn anschlie\u00dfend aus diesem Backup wiederherstellen.\n\nBitte beachten Sie, dass das Backup keine Hintergrundbilder enth\u00e4lt. Voreingestellte Hintergrundbilder werden nicht gesichert, und es werden keine Hintergrundbilder (weder voreingestellte noch benutzerdefinierte) als Teil der Backup-Wiederherstellung wiederhergestellt.",
  "pl": "Ta aktualizacja zmienia system plik\u00f3w tapet. W zwi\u0105zku z tym, po aktualizacji z jakiejkolwiek wersji oprogramowania wcze\u015bniejszej ni\u017c v1.49, system plik\u00f3w tapet (wraz ze wszystkimi zapisanymi tapetami) zostanie usuni\u0119ty.\n\nPoniewa\u017c ta wersja znacznie poprawia proces przesy\u0142ania tapet za pomoc\u0105 aplikacji i panelu nawigacyjnego (dashboard), po aktualizacji oprogramowania konieczne b\u0119dzie ponowne zainstalowanie tapet. Mo\u017cesz je wybra\u0107 ponownie z wbudowanych ustawie\u0144 fabrycznych lub ponownie przes\u0142a\u0107 wcze\u015bniej przeniesione tapety niestandardowe.\n\nDodatkowo zaktualizowano system plik\u00f3w historii. Podczas aktualizacji istniej\u0105ce wpisy historii zostan\u0105 automatycznie poddane migracji. Chocia\u017c migracja ma na celu zachowanie danych, zdecydowanie zaleca si\u0119 utworzenie pe\u0142nej kopii zapasowej r\u00f3\u017ca\u0144ca (za pomoc\u0105 aplikacji lub panelu nawigacyjnego) przed aktualizacj\u0105. Je\u015bli historia ulegnie uszkodzeniu z jakiegokolwiek powodu, mo\u017cna j\u0105 nast\u0119pnie przywr\u00f3ci\u0107 z tej kopii zapasowej.\n\nNale\u017cy pami\u0119ta\u0107, \u017ce kopia zapasowa nie obejmuje tapet. Fabrycznie zainstalowane tapety nie s\u0105 archiwizowane i \u017cadne tapety (fabryczne ani niestandardowe) nie s\u0105 przywracane w ramach procesu przywracania kopii zapasowej.",
  "fr": "Cette mise \u00e0 jour modifie le syst\u00e8me de fichiers des fonds d'\u00e9cran. Par cons\u00e9quent, apr\u00e8s la mise \u00e0 niveau depuis n'importe quelle version du micrologiciel ant\u00e9rieure \u00e0 la v1.49, le syst\u00e8me de fichiers des fonds d'\u00e9cran (y compris tous les fonds d'\u00e9cran stock\u00e9s) sera effac\u00e9.\n\n\u00c9tant donn\u00e9 que cette version am\u00e9liore consid\u00e9rablement le processus de t\u00e9l\u00e9chargement des fonds d'\u00e9cran via l'application et le tableau de bord, vous devrez r\u00e9installer vos fonds d'\u00e9cran apr\u00e8s la mise \u00e0 niveau du micrologiciel. Vous pouvez soit les s\u00e9lectionner \u00e0 nouveau parmi les pr\u00e9r\u00e9glages int\u00e9gr\u00e9s, soit ret\u00e9l\u00e9charger vos fonds d'\u00e9cran personnalis\u00e9s transf\u00e9r\u00e9s pr\u00e9c\u00e9demment.\n\nDe plus, le syst\u00e8me de fichiers de l'historique a \u00e9t\u00e9 mis \u00e0 jour. Pendant la mise \u00e0 niveau, les entr\u00e9es d'historique existantes seront migr\u00e9es automatiquement. Bien que la migration soit con\u00e7ue pour pr\u00e9server vos donn\u00e9es, il est fortement recommand\u00e9 de cr\u00e9er une sauvegarde compl\u00e8te du Rosaire (en utilisant l'application ou le tableau de bord) avant la mise \u00e0 niveau. Si l'historique est corrompu pour une raison quelconque, vous pourrez le restaurer \u00e0 partir de cette sauvegarde par la suite.\n\nVeuillez noter que la sauvegarde n'inclut pas les fonds d'\u00e9cran. Les fonds d'\u00e9cran pr\u00e9d\u00e9finis ne sont pas sauvegard\u00e9s et aucun fond d'\u00e9cran (pr\u00e9d\u00e9fini ou personnalis\u00e9) n'est restaur\u00e9 dans le cadre du processus de restauration de la sauvegarde.",
  "es": "Esta actualizaci\u00f3n cambia el sistema de archivos de fondos de pantalla. Como resultado, despu\u00e9s de actualizar desde cualquier versi\u00f3n de firmware anterior a la v1.49, el sistema de archivos de fondos de pantalla (incluidos todos los fondos almacenados) se borrar\u00e1.\n\nDado que esta versi\u00f3n mejora significativamente el proceso de carga de fondos de pantalla a trav\u00e9s de la aplicaci\u00f3n y el panel de control, deber\u00e1 volver a instalar sus fondos de pantalla despu\u00e9s de la actualizaci\u00f3n del firmware. Puede seleccionarlos de nuevo entre los ajustes preestablecidos integrados o volver a cargar sus fondos de pantalla personalizados transferidos anteriormente.\n\nAdem\u00e1s, el sistema de archivos del historial ha sido actualizado. Durante la actualizaci\u00f3n, las entradas del historial existentes se migrar\u00e1n autom\u00e1ticamente. Aunque la migraci\u00f3n est\u00e1 dise\u00f1ada para preservar sus datos, se recomienda encarecidamente crear una copia de seguridad completa del Rosario (usando la aplicaci\u00f3n o el panel de control) antes de actualizar. Si el historial se corrompe por alg\u00fan motivo, puede restaurarlo posteriormente desde esta copia de seguridad.\n\nTenga en cuenta que la copia de seguridad no incluye fondos de pantalla. Los fondos de pantalla preestablecidos no se guardan en la copia de seguridad, y no se restaura ning\u00fan fondo de pantalla (preestablecido o personalizado) como parte del proceso de restauraci\u00f3n.",
  "pt": "Esta atualiza\u00e7\u00e3o altera o sistema de arquivos dos pap\u00e9is de parede. Como resultado, ap\u00f3s a atualiza\u00e7\u00e3o de qualquer vers\u00e3o de firmware anterior \u00e0 v1.49, o sistema de arquivos de pap\u00e9is de parede (incluindo todos os pap\u00e9is de parede armazenados) ser\u00e1 apagado.\n\nComo esta vers\u00e3o melhora significativamente o processo de upload de pap\u00e9is de parede atrav\u00e9s do aplicativo e do painel de controle (dashboard), voc\u00ea precisar\u00e1 reinstalar seus pap\u00e9is de parede ap\u00f3s a atualiza\u00e7\u00e3o do firmware. Voc\u00ea pode selecion\u00e1-los novamente nas predefini\u00e7\u00f5es incorporadas ou reenviar seus pap\u00e9is de parede personalizados transferidos anteriormente.\n\nAl\u00e9m disso, o sistema de arquivos do hist\u00f3rico foi atualizado. Durante a atualiza\u00e7\u00e3o, as entradas do hist\u00f3rico existentes ser\u00e3o migradas automaticamente. Embora a migra\u00e7\u00e3o seja projetada para preservar seus dados, \u00e9 altamente recomend\u00e1vel criar um backup completo do Ros\u00e1rio (usando o aplicativo ou o painel de controle) antes de atualizar. Se o hist\u00f3rico for corrompido por qualquer motivo, voc\u00ea poder\u00e1 restaur\u00e1-lo a partir deste backup posteriormente.\n\nObserve que o backup n\u00e3o inclui pap\u00e9is de parede. Os pap\u00e9is de parede predefinidos n\u00e3o fazem parte do backup e nenhum papel de parede (predefinido ou personalizado) \u00e9 restaurado como parte do processo de restaura\u00e7\u00e3o do backup."
  }
};
window.SMARTROSARY_RELEASE_MESSAGE = {
  "en": "Firmware v1.54 brings OTA upgrade status screens on the device itself and improves RTC synchronization reliability.",
  "de": "Firmware v1.54 bringt OTA-Upgrade-Statusbildschirme auf dem Ger\u00e4t selbst und verbessert die Zuverl\u00e4ssigkeit der RTC-Synchronisation.",
  "pl": "Firmware v1.54 wprowadza ekrany statusu aktualizacji OTA na samym urz\u0105dzeniu i poprawia niezawodno\u015b\u0107 synchronizacji RTC.",
  "fr": "Le firmware v1.54 apporte des \u00e9crans d'\u00e9tat de mise \u00e0 niveau OTA sur l'appareil lui-m\u00eame et am\u00e9liore la fiabilit\u00e9 de synchronisation RTC.",
  "es": "El firmware v1.54 trae pantallas de estado de actualizaci\u00f3n OTA en el propio dispositivo y mejora la fiabilidad de sincronizaci\u00f3n RTC.",
  "pt": "O firmware v1.54 traz telas de status de atualiza\u00e7\u00e3o OTA no pr\u00f3prio dispositivo e melhora a confiabilidade da sincroniza\u00e7\u00e3o RTC."
};
